[package]
name = "merman_langserver"
edition.workspace = true
version.workspace = true

[dependencies]
schemars = "1"
schemask_core = "0.1.6"
schemask_derive = "0.1.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "merman-langserver-schema"
path = "src/bin/schema.rs"
