[package]
name = "merman"
edition.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "merman"
path = "src/main.rs"

[[bin]]
name = "merman-tool"
path = "src/tool.rs"

[dependencies]
merman_core = { path = "../core" }
merman_api = { path = "../api" }
aargvark = "0.12"
serde_json = { version = "1", features = ["preserve_order", "unbounded_depth"] }
htwrap = "0.15"
http = "1"
http-body-util = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "process", "io-util", "sync", "time"] }
loga = { version = "0.5.5", features = ["serde"] }
open = "5"
serde = { version = "1", features = ["derive"] }
directories = "6"
tao = "0.37"
wry = "0.57"
notify = "8"
futures = "0.3"
hyper-tungstenite = "0.17"
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
foyer = "0.22.6"
regex = "1"
uuid = { version = "1.26.1", features = ["v4"] }
notify-rust = { version = "4.18.0", default-features = false, features = ["z-with-tokio"] }
