[package]
name = "merman_web"
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
merman_core = { path = "../core" }
merman_api = { path = "../api" }
glove = "0.5"
serde_json = { version = "1", features = ["preserve_order", "unbounded_depth"] }
wasm-bindgen = "=0.2.121"
wasm-bindgen-futures = "0.4"
futures = "0.3"
js-sys = "0.3"
rooting = { version = "0.2", features = ["futures"] }
gloo-utils = "0.2"
gloo-events = "0.2"
gloo-render = "0.2"
gloo-timers = "0.3"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "TextMetrics",
    "DomRect",
    "CssStyleDeclaration",
    "Node",
    "Event",
    "EventTarget",
    "WebSocket",
    "MessageEvent",
    "Location",
    "Selection",
    "MouseEvent",
    "WheelEvent",
    "KeyboardEvent",
    "Navigator",
    "Clipboard",
    "Request",
    "RequestInit",
    "Response",
    "SvgTextContentElement",
    "SvgGraphicsElement",
    "SvgElement",
    "SvgRect",
] }
